#!/bin/sh
# Init script for Yandex Smart Home provider Docker dev environment.
# Auto-generated by ma-provider-tools — do not edit manually.
set -e

echo "==> Setting up Yandex Smart Home provider..."

# Locate MA providers directory inside the container venv
PROVIDERS_DIR=$(/app/venv/bin/python3 -c \
    "import music_assistant.providers, os; print(os.path.dirname(music_assistant.providers.__file__))")

# Remove any existing yandex_music provider (image may bundle one), then symlink ours
rm -rf "${PROVIDERS_DIR}/yandex_smarthome"
ln -s /tmp/provider "${PROVIDERS_DIR}/yandex_smarthome"
echo "==> Provider linked: ${PROVIDERS_DIR}/yandex_smarthome"

# Install provider-specific runtime dependencies (skips music_assistant itself)
DEPS=$(/app/venv/bin/python3 - <<'PYEOF'
import sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
try:
    with open("/tmp/pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    deps = [
        d for d in data.get("project", {}).get("dependencies", [])
        if not d.lower().startswith("music_assistant")
    ]
    print(" ".join(deps))
except Exception:
    pass
PYEOF
)
if [ -n "$DEPS" ]; then
    echo "==> Installing provider dependencies: $DEPS"
    /app/venv/bin/pip install --quiet $DEPS
fi

# Install manifest.json requirements (e.g. ya-passport-auth)
MANIFEST_DEPS=$(/app/venv/bin/python3 - <<'PYEOF'
import json
try:
    with open("/tmp/provider/manifest.json") as f:
        m = json.load(f)
    print(" ".join(m.get("requirements", [])))
except Exception:
    pass
PYEOF
)
if [ -n "$MANIFEST_DEPS" ]; then
    echo "==> Installing manifest requirements: $MANIFEST_DEPS"
    if [ -x /app/venv/bin/uv ]; then
        /app/venv/bin/uv pip install --quiet $MANIFEST_DEPS
    elif [ -x /app/venv/bin/pip ]; then
        /app/venv/bin/pip install --quiet $MANIFEST_DEPS
    else
        pip install --quiet $MANIFEST_DEPS
    fi
fi

echo "==> Starting Music Assistant..."
exec /usr/local/bin/entrypoint.sh --data-dir /data --cache-dir /data/.cache
